/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.Collections;

public class Library {


    public static void main(String[] args) {
//        System.out.println("hi");
//        System.out.println("hello");
//        int numTest = 5;
//        System.out.println(Arrays.toString(roll(numTest)));

//        int[] testArr1 = {1,2,3};
//
//        System.out.println(checkDuplicates(testArr1));

//
    }

    public int[] roll(int number) {

        int[] trialArr = new int[number];

        for (int i = 0; i < trialArr.length; i++) {
            trialArr[i] = (int) (5 * Math.random()) + 1;
        }
        return trialArr;
    }

    public boolean checkDuplicates(int[] arr) {
        boolean returnedBoolean = false;
        for (int i = 0; i < arr.length; i++) {
            for (int j = i+1; j < arr.length; j++) {
                if (arr[i] == arr[j]){
                    returnedBoolean = true;
                }
            }
        }
        return returnedBoolean;
    }


    public double simpleAvg(int[] arr2) {
        int sum = 0;
        for (int i = 0; i < arr2.length; i++) {
            sum = sum + arr2[i];
        }
        double avgOfArr = (double) sum / arr2.length;
        return avgOfArr;
    }



    public int[] minAvgOfArrOfArrays(int[][] array){

        ArrayList<Double> arrayOfAvgs = new ArrayList<>();

        for(int i=0; i<array.length;i++){
            double sum=0;
            for(int j = 0 ; j<array[i].length;j++){
                sum+=array[i][j];
            }
            arrayOfAvgs.add(sum/array[i].length);
        }
        return array[arrayOfAvgs.indexOf(Collections.min(arrayOfAvgs))];
    }

}


